#!/usr/bin/env bash
#
# Merge current branch into a selected branch.

set -eo pipefail

. ~/.dotfiles/scripts/lib/prompt.sh

branch="$(git symbolic-ref --short HEAD)"

$(dirname "$BASH_SOURCE")/git-branch

reply=$(yesno "Do you want to push after merging? (Y/n)" "yes")
git pull && git merge $branch
if [ "$reply" = "yes" ]; then
  git push
fi
