#!/usr/bin/env bash
#
# Merge a selected branch into current branch.

set -eo pipefail

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

. "$(dirname "$BASH_SOURCE")/git-common"
. "$dotfiles_dir/scripts/lib/prompt.sh"

select_branch --result

selection="${result[0]}"
if [ -n "$selection" ]; then
  reply=$(yesno "Do you want to push after merging? (Y/n)" "yes")
  git merge "$selection"
  if [ "$reply" = "yes" ]; then
    git push
  fi
fi
