#!/usr/bin/env bash
#
# Merge a selected branch into current branch.

set -eo pipefail

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

. "$(dirname "$BASH_SOURCE")/git-common"
. "$dotfiles_dir/scripts/lib/prompt.sh"

select_branch --result

selection="${result[0]}"
if [ -n "$selection" ]; then
  rebase="$(yesno "Do you want to rebase? (y/N)" "no")"
  push="$(yesno "Do you want to push after merging? (Y/n)" "yes")"
  if [ "$rebase" = "no" ]; then
    git merge "$selection"
  else
    git rebase "$selection"
  fi
  if [ "$push" = "yes" ]; then
    git push
  fi
fi
