#!/usr/bin/env bash
#
# Install acme (https://github.com/acmesh-official/acme.sh)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

dest_path="$DOTFILES_TARGET_DIR/opt/acme.sh"

download_and_install_by_git "https://github.com/acmesh-official/acme.sh.git" "" "$dest_path"
