#!/usr/bin/env bash
#
# Install alacritty (https://github.com/alacritty/alacritty/blob/master/INSTALL.md)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command alacritty &> /dev/null && exit

if has_apt; then
  sudo apt-get install -y cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev >/dev/null
else
  abort "Unsupported system"
fi

do_install() {
  cd "$1"

  rustup override set stable
  rustup update stable

  cargo build --release

  # Install `alacritty` terminfo.
  sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

  # Install desktop entry.
  sudo cp target/release/alacritty /usr/local/bin
  sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
  sudo desktop-file-install extra/linux/Alacritty.desktop
  sudo update-desktop-database
}

dir="/tmp/alacritty"
git_clone https://github.com/alacritty/alacritty.git "$dir" --depth 1

do_install "$dir"
rm -rf "$dir"
