#!/usr/bin/env bash
#
# Install aliyun-cli (https://github.com/aliyun/aliyun-cli)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command aliyun &> /dev/null && exit

version="3.0.77"
path_to_save="/tmp/aliyun-cli-$version.tgz"
if is_mac; then
  platform="macosx"
elif is_linux; then
  platform="linux"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/cget" "https://aliyuncli.alicdn.com/aliyun-cli-$platform-$version-amd64.tgz" "$path_to_save"
tar zxf "$path_to_save" -C "$DOTFILES_TARGET_DIR/bin"
rm -rf "$path_to_save"
