#!/usr/bin/env bash
#
# Install aliyun-cli (https://github.com/aliyun/aliyun-cli)

set -eo pipefail

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

source "$dotfiles_dir/scripts/lib/path.sh"
PATH="$(new_path_exclude "$dotfiles_dir/bin")"

type -p aliyun &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

version="3.0.77"
path_to_save="/tmp/aliyun-cli-$version.tgz"
if is_mac; then
  platform="macosx"
elif is_linux; then
  platform="linux"
else
  abort "Unsupported system"
fi

"$dotfiles_dir/bin/cget" "https://aliyuncli.alicdn.com/aliyun-cli-$platform-$version-amd64.tgz" "$path_to_save"
tar zxf "$path_to_save" -C ~/bin
rm -rf "$path_to_save"
