#!/usr/bin/env bash
#
# Install antibody

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

PATH="$DOTFILES_TARGET_DIR/bin:$PATH"
check_command antibody &> /dev/null && exit

version="v6.1.1"
path_to_save="/tmp/antibody-$version.tgz"
if is_mac; then
  platform="Darwin"
elif is_linux; then
  platform="Linux"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://github.com/getantibody/antibody/releases/download/$version/antibody_${platform}_x86_64.tar.gz" "$path_to_save"
tar zxf "$path_to_save" -C /tmp antibody
if [ -n "$DOTFILES_NON_INTRUSIVE_MODE" ]; then
  mv /tmp/antibody "$DOTFILES_TARGET_DIR/bin"
else
  sudo mv /tmp/antibody /usr/local/bin
fi
rm "$path_to_save"
