#!/usr/bin/env bash
#
# Install antibody

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command antibody &> /dev/null && exit

if is_arm64; then
  "$DOTFILES_DIR/scripts/install/asdf"

  if [ -z "$ASDF_DATA_DIR" ]; then
    export ASDF_DATA_DIR="$DOTFILES_TARGET_DIR/.asdf"
  fi

  "$DOTFILES_DIR/scripts/install/golang"

  source "$DOTFILES_DIR/scripts/lib/asdf.sh"

  asdf shell golang "$(parse_package_version golang)"

  install_fn() {
    cd "$1"

    go get -u golang.org/x/sys
    make build
    mv antibody "$DOTFILES_TARGET_DIR/bin"
  }

  download_and_install_by_git "https://github.com/getantibody/antibody.git" install_fn
  exit
fi

version="v6.1.1"
path_to_save="/tmp/antibody-$version.tgz"
if is_mac; then
  platform="Darwin"
elif is_linux; then
  platform="Linux"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://github.com/getantibody/antibody/releases/download/$version/antibody_${platform}_x86_64.tar.gz" "$path_to_save"
tar zxf "$path_to_save" -C /tmp antibody
mv /tmp/antibody "$DOTFILES_TARGET_DIR/bin"
rm "$path_to_save"
