#!/usr/bin/env bash
#
# Install apktool (https://ibotpeaches.github.io/Apktool/install/)

set -eo pipefail

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

source "$dotfiles_dir/scripts/lib/path.sh"
PATH="$(new_path_exclude "$dotfiles_dir/bin")"

. $(dirname "$BASH_SOURCE")/../lib/install.sh

type -p apktool &> /dev/null && exit

version="2.6.0"
if is_mac; then
  wrapper_url="https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/osx/apktool"
elif is_linux; then
  wrapper_url="https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
else
  abort "Unsupported system"
fi

"$dotfiles_dir/bin/cget" "$wrapper_url" /tmp/apktool
"$dotfiles_dir/bin/cget" "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_$version.jar" /tmp/apktool.jar

chmod a+x /tmp/apktool /tmp/apktool.jar
sudo mv /tmp/apktool /tmp/apktool.jar /usr/local/bin
