#!/usr/bin/env bash
#
# Install apktool (https://ibotpeaches.github.io/Apktool/install/)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command apktool &> /dev/null && exit

version="2.6.0"
if is_mac; then
  wrapper_url="https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/osx/apktool"
elif is_linux; then
  wrapper_url="https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "$wrapper_url" /tmp/apktool
"$DOTFILES_DIR/bin/get" "https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_$version.jar" /tmp/apktool.jar

chmod a+x /tmp/apktool /tmp/apktool.jar
mv /tmp/apktool /tmp/apktool.jar "$DOTFILES_TARGET_DIR/bin"
