#!/usr/bin/env bash
#
# Install arthas (https://github.com/alibaba/arthas)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

. $(dirname "$BASH_SOURCE")/../lib/install.sh

target_dir="$HOME/arthas"
[ -f "$target_dir/as.sh" ] && exit

version="3.6.1"
path_to_save="/tmp/arthas-$version.zip"
"$DOTFILES_DIR/bin/get" "https://github.com/alibaba/arthas/releases/download/arthas-all-$version/arthas-bin.zip" "$path_to_save"
unzip -q "$path_to_save" -d "$target_dir"
rm -rf "$path_to_save"
