#!/usr/bin/env bash

set -eo pipefail

export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

if [ ! -d "$DOTFILES_TARGET_DIR/.asdf" ]; then
  git clone --depth 1 https://github.com/asdf-vm/asdf.git "$DOTFILES_TARGET_DIR/.asdf"
fi
