#!/usr/bin/env bash
#
# Install bc.

set -eo pipefail

type -p bc &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if has_yum; then
  sudo yum install -y bc
else
  abort "Unsupported system"
fi
