#!/usr/bin/env bash
#
# Install GNU binutils for Mac OSX.
#
# On Mac OSX, We use binutils provided by pwntools, because homebrew official
# binutils doesn't include `as` command.
# See issue [here](https://github.com/Homebrew/homebrew-core/issues/29177).

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  type -p x86_64-unknown-linux-gnu-as &> /dev/null && exit

  # Below codes are copied from
  # `https://github.com/Gallopsled/pwntools-binutils/blob/master/macos/binutils-x86_64.rb`.
  # The reason we copied is we want the package name to be `binutils-pwntools`
  # after installation, but brew doesn't support specifying a name option, so
  # we need to rename both the file and the class name manually.
  #
  # TODO check the arch
  create_tmpdir tmpdir
  tmpfile="$tmpdir/binutils-pwntools.rb"
  cat <<'EOF' >"$tmpfile"
class BinutilsPwntools < Formula
  homepage "https://www.gnu.org/software/binutils/binutils.html"
  url "https://ftpmirror.gnu.org/binutils/binutils-2.34.tar.gz"
  mirror "https://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.gz"
  sha256 "53537d334820be13eeb8acb326d01c7c81418772d626715c7ae927a7d401cab3"

  # No --default-names option as it interferes with Homebrew builds.

  def install
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--prefix=#{prefix}",
                          "--target=x86_64-unknown-linux-gnu",
                          "--disable-static",
                          "--disable-multilib",
                          "--disable-nls",
                          "--disable-werror"
    system "make", "-j"
    system "make", "install"
    system "rm", "-rf", "#{prefix}/share/info"
  end

  test do
    assert .include? 'main'
    assert_equal 0, 0.exitstatus
  end
end
EOF
  brew_install "$tmpfile"
fi
