#!/usr/bin/env bash
#
# Install bpftrace (https://github.com/bpftrace/bpftrace)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command bpftrace &> /dev/null && exit

if has_apt; then
  sudo apt-get install -y bpftrace
else
  abort "Unsupported system"
fi
