#!/usr/bin/env bash
#
# Install clangd (https://clangd.llvm.org/installation.html).

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

type -p clangd &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  brew_install llvm
elif is_linux; then
  # clangd depends on glibc 2.18. Manually run `$DOTFILES_DIR/scripts/install/glibc 2.18'
  version="10.0.0"
  path_to_save="/tmp/clangd-$version.zip"
  "$DOTFILES_DIR/bin/get" "https://github.com/clangd/clangd/releases/download/$version/clangd-linux-$version.zip" $path_to_save
  cd /tmp && unzip $path_to_save
  cp /tmp/clangd_$version/bin/clangd ~/bin
  rm -rf /tmp/clangd_$version
else
  abort "Unsupported system"
fi
