#!/usr/bin/env bash
#
# Install class-dump (https://github.com/nygard/class-dump)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

. $(dirname "$BASH_SOURCE")/../lib/install.sh

check_command class-dump &> /dev/null && exit

version="3.5"
path_to_save="/tmp/class-dump-$version.tgz"
if ! is_mac; then
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "http://stevenygard.com/download/class-dump-$version.tar.gz" "$path_to_save"

tar zxf "$path_to_save" -C ~/tmp/foo --strip-components=1 --wildcards "class-dump-$version/class-dump"
rm -rf "$path_to_save"
