#!/usr/bin/env bash
#
# Install clink. (https://mridgers.github.io/clink/)

. $(dirname "$BASH_SOURCE")/../lib/install.sh

scoop="$(dirname "$BASH_SOURCE")/../../bin/scoop"

"$scoop" install clink
cmd.exe /c clink autorun install
