#!/usr/bin/env bash
#
# Install cmake.

type -p cmake &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if has_yum; then
  sudo yum install -y cmake
else
  abort "Unsupported system"
fi
