#!/usr/bin/env bash
#
# Install coc.nvim extensions. (https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#automation-script)

. $(dirname "$BASH_SOURCE")/../lib/install.sh

usage() {
  cat <<-EOF
Usage: $0 <extension>
Install coc extensions.

Supported extensions include:

  * ultisnips
  * java
  * python
  * clangd
  * omnisharp
  * sourcekit
  * tsserver
EOF
  exit 1
}

rootdir="$HOME/.config/coc/extensions"

mkdir -p "$rootdir"
cd "$rootdir"

npm_install() {
  npm install --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod "$@"
}

extension="$1"
extensions=(
  ultisnips
  java
  python
  clangd
  omnisharp
  sourcekit
  tsserver
)
if [ -z "$extension" ]; then
  extension="$(IFS=$'\n'; echo "${extensions[*]}" | fzf +m)"
  [ -z "$extension" ] && exit 1
fi

case "$extension" in
  ultisnips)
    npm_install coc-ultisnips@1.2.3
    ;;
  java)
    npm_install coc-java@1.5.3
    serverdir="coc-java-data/server"
    dstpath="/tmp/jdtls.tar.gz"
    mkdir -p "$serverdir"
    ~/.dotfiles/bin/cget "http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz" "$dstpath"
    tar zxf "$dstpath" -C "$serverdir"
    rm "$dstpath"
    ;;
  python)
    npm_install coc-python@1.2.13
    ;;
  clangd)
    npm_install coc-clangd@0.4.7
    ;;
  omnisharp)
    npm_install coc-omnisharp@0.0.26
    ;;
  sourcekit)
    npm_install coc-sourcekit@0.0.2
    ;;
  tsserver)
    npm_install coc-sourcekit@1.5.1
    ;;
  *)
    usage
    ;;
esac
