#!/usr/bin/env bash
#
# Install CoreDNS (https://github.com/coredns/coredns).

set -e

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

type -p coredns &> /dev/null && exit

. "$DOTFILES_DIR/scripts/lib/install.sh"

version="1.8.0"
path_to_save="/tmp/coredns-$version.tgz"
if is_mac; then
  platform="darwin"
elif is_linux; then
  platform="linux"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://github.com/coredns/coredns/releases/download/$version/coredns_${version}_${platform}_amd64.tgz" "$path_to_save"

if is_mac; then
  tar zxf "$path_to_save" -C ~/bin
elif is_linux; then
  sudo tar zxf "$path_to_save" -C /usr/bin
fi

rm -f "$path_to_save"
