#!/usr/bin/env bash
#
# Install latest curl (https://curl.haxx.se/).
#
# We actually want to use '--connect-to' option (see https://curl.haxx.se/docs/manpage.html#--connect-to).
# See also '--resolve'.

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

. "$DOTFILES_DIR/scripts/lib/utils/common.sh"
. "$DOTFILES_DIR/scripts/lib/utils/lines_to_array.sh"
. "$DOTFILES_DIR/scripts/lib/utils/split.sh"
. "$DOTFILES_DIR/scripts/lib/utils/version.sh"

version="7.71.1"
type -p curl &>/dev/null && ! version_lt "$(curl -V | head -1 | cut -d' ' -f 2)" "$version" && exit

path_to_save="/tmp/curl-$version.tar.xz"
"$DOTFILES_DIR/bin/get" "https://curl.haxx.se/download/curl-$version.tar.xz" $path_to_save
tar Jxf $path_to_save -C /tmp

cd /tmp/curl-$version
./configure
make
sudo make install

sudo rm -rf $path_to_save /tmp/curl-$version
