#!/usr/bin/env bash
#
# Install docker (https://docs.docker.com/engine/install/)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

usage() {
  cat <<-EOF
Usage: $0

Install docker.

Options:
  -N Do not use mirror
EOF
  exit 1
}

parse_args="
  -N)
    no_mirror=1
    ;;
  *)
    usage
    ;;
"

source "$DOTFILES_DIR/scripts/lib/install.sh"

# Ensure current user is in docker group.
check_group() {
  if ! groups | grep docker &> /dev/null; then
    sudo usermod -a -G docker "$USER"
    echo "You've been appended to docker group. To make it effective, you need to logout and login again."
  fi
}

check_enabled() {
  if [ "$(sudo systemctl is-enabled docker)" = "disabled" ]; then
    sudo systemctl enable docker
  fi
}

if ! has_yum && ! has_apt; then
  abort "Unsupported system"
fi

check_command docker &> /dev/null && check_group && check_enabled && exit

if has_yum; then
  # See https://github.com/containerd/containerd/issues/6209
  sudo yum install -y libseccomp-devel

  # Mirrors:
  # * https://developer.aliyun.com/mirror/docker-ce
  # * https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/
  sudo wget -O /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/centos/docker-ce.repo
  if [ -z "$no_mirror" ]; then
    sudo sed -i 's+download.docker.com+mirrors.aliyun.com/docker-ce+' /etc/yum.repos.d/docker-ce.repo
  fi
  sudo yum install -y docker-ce docker-ce-cli
elif has_apt;  then
  # Ref: https://docs.docker.com/engine/install/ubuntu/
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt-get update
  sudo apt-get -y install docker-ce docker-ce-cli containerd.io
fi

check_group
check_enabled
sudo systemctl start docker

# Check if docker is installed successfully.
docker run hello-world
