#!/usr/bin/env bash
#
# Install fd (https://github.com/sharkdp/fd)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command fd &> /dev/null && exit

if is_mac && [ -z "$DOTFILES_NON_INTRUSIVE_MODE" ]; then
  brew_install fd
else
  version=8.7.1
  install_fn() {
    local dir="$(find "$1" -maxdepth 1 -type d | grep -v '^\.$' | tail -1)"
    cd "$dir"
    if [ -n "$DOTFILES_NON_INTRUSIVE_MODE" ]; then
      cp fd $DOTFILES_TARGET_DIR/bin
    else
      sudo cp fd /usr/local/bin/ && sudo cp fd.1 /usr/local/share/man/man1/ && sudo mandb
    fi
  }

  if is_arm64; then
    if is_mac; then
      abort "Unsupported arch"
    else
      platform="aarch64-unknown-linux-gnu"
    fi
  else
    if is_mac; then
      platform="x86_64-apple-darwin"
    else
      platform="x86_64-unknown-linux-musl"
    fi
  fi

  download_and_install "https://github.com/sharkdp/fd/releases/download/v${version}/fd-v${version}-${platform}.tar.gz" install_fn
fi
