#!/usr/bin/env bash
#
# Install frida-gadget (https://github.com/frida/frida)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

copy_to_objection_dir() {
  local -a dirs
  case "$1" in
    android-arm)
      dirs=(armeabi armeabi-v7a)
      ;;
    android-arm64)
      dirs=(arm64 arm64-v8a)
      ;;
    android-x86)
      dirs=(x86)
      ;;
    android-x86_64)
      dirs=(x86_64)
      ;;
  esac

  local confirmed
  for name in "${dirs[@]}"; do
    dest="$HOME/.objection/android/$name/libfrida-gadget.so"
    if [ -e "$dest" -a -z "$confirmed" ]; then
      source "$DOTFILES_DIR/scripts/lib/prompt.sh"
      echo "A gadget already exists in the objection directory. Do you want to overwrite it?"
      if [ "$(yesno "(Y/n): " "yes")" = "no" ]; then
        exit
      fi
      confirmed=1
    fi
    mkdir -p "$(dirname "$dest")"
    cp "$2" "$dest"
    echo "Gadget copied to $dest"
  done
}

install_gadget() {
  local platform="$1"
  local version="$2"
  local extension="$3"
  local file_name="frida-gadget-$version-$platform.$extension"
  local file_path="$HOME/frida/$file_name"
  if [ ! -e "$file_path" ]; then
    echo "Install gadget for $platform@$version"
    local path_to_save="/tmp/$file_name.xz"
    "$DOTFILES_DIR/bin/get" "https://github.com/frida/frida/releases/download/$version/$file_name.xz" "$path_to_save"

    mkdir -p "$(dirname "$file_path")"
    xz -dc "$path_to_save" >"$file_path"
    rm -rf "$path_to_save"
    echo "Installed to $file_path."
  else
    echo "Gadget already installed."
  fi

  copy_to_objection_dir "$platform" "$file_path"
}

platforms="ios-universal
android-arm
android-arm64
android-x86
android-x86_64"

platform="$(echo "$platforms" | fzf --prompt "Select a platform to install: ")"

version=16.0.2
case "$platform" in
  ios-universal)
    extension="dylib"
    ;;
  android-*)
    extension="so"
    ;;
  *)
    abort "Unsupported platform $platform"
    ;;
esac
install_gadget "$platform" "$version" "$extension"
