#!/usr/bin/env bash
#
# Install fzf (https://github.com/junegunn/fzf)

set -eo pipefail

type -p fzf &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  brew_install fzf
  /usr/local/opt/fzf/install --key-bindings --completion --no-update-rc
else
  if $(test -d ~/.fzf && cd ~/.fzf && git status &>/dev/null); then
    git pull
  else
    rm -rf ~/.fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  fi
  ~/.fzf/install --key-bindings --completion --no-update-rc
fi
