#!/usr/bin/env bash
#
# Install fzf (https://github.com/junegunn/fzf)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command fzf &> /dev/null && exit

export XDG_CONFIG_HOME="$DOTFILES_TARGET_DIR/.config"

if is_mac && [ -z "$DOTFILES_NON_INTRUSIVE_MODE" ]; then
  brew_install fzf
  /usr/local/opt/fzf/install --xdg --all --no-update-rc
else
  if test -d "$DOTFILES_TARGET_DIR/.fzf" && cd "$DOTFILES_TARGET_DIR/.fzf" && git status &>/dev/null; then
    git pull
  else
    rm -rf "$DOTFILES_TARGET_DIR/.fzf"
    git clone --depth 1 https://github.com/junegunn/fzf.git "$DOTFILES_TARGET_DIR/.fzf"
  fi
  "$DOTFILES_TARGET_DIR/.fzf/install" --xdg --all --no-update-rc
fi
