#!/usr/bin/env bash
#
# Install git (http://git-scm.com/download/linux)

set -eo pipefail

type -p git &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

version="2.31.1"
path_to_save="/tmp/git-$version.tar.xz"
~/.dotfiles/bin/cget "https://mirrors.edge.kernel.org/pub/software/scm/git/git-$version.tar.xz" "$path_to_save"

cd /tmp
tar Jxf "$path_to_save"

if has_yum; then
  sudo yum install -y curl-devel expat-devel gettext-devel \
    openssl-devel perl-devel zlib-devel
fi

cd "git-$version"
./configure
make
sudo make install

rm -rf "$path_to_save" "/tmp/git-$version"
