#!/usr/bin/env bash
#
# Install git (http://git-scm.com/download/linux)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

usage() {
  cat <<-EOF
Install git.

Options:
  --local-install Install to user home directory
  --force-install Force to install even if it already exists
EOF
  exit 1
}

parse_args="
  --local-install)
    local_install=1
    ;;
  --force-install)
    force_install=1
    ;;
  *)
    usage
    ;;
"

source "$DOTFILES_DIR/scripts/lib/install.sh"

[ -z "$force_install" ] && check_command git &> /dev/null && exit

version="2.31.1"

install_fn() {
  local dir="$(find "$1" -maxdepth 1 -type d | grep -v '^\.$' | tail -1)"
  cd "$dir"

  if has_yum; then
    sudo yum install -y curl-devel expat-devel gettext-devel \
      openssl-devel perl-devel zlib-devel
  fi

  if [ -z "$DOTFILES_NON_INTRUSIVE_MODE" -a -z "$local_install" ]; then
    ./configure
    make
    sudo make install
  else
    local dest_path="$DOTFILES_TARGET_DIR/opt/git-$version"
    ./configure --prefix="$dest_path"
    make
    make install

    local link="$DOTFILES_TARGET_DIR/bin/git"
    mkdir -p "$DOTFILES_TARGET_DIR/bin"
    [ -e "$link" ] && rm -rf "$link"
    create_link "$link" "$dest_path/bin/git"
  fi
}

download_and_install "https://mirrors.edge.kernel.org/pub/software/scm/git/git-$version.tar.xz" install_fn
