#!/usr/bin/env bash
#
# Install google-chrome on Linux server.

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command google-chrome &> /dev/null && exit

version="3.0.77"
if has_apt; then
  path_to_save="/tmp/google-chrome-stable_current_amd64.deb"
  "$DOTFILES_DIR/bin/get" https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb "$path_to_save"
  sudo dpkg -i "$path_to_save"
  sudo apt install -y --fix-broken
elif has_yum; then
  path_to_save="/tmp/google-chrome-stable_current_x86_64.rpm"
  "$DOTFILES_DIR/bin/get" https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm "$path_to_save"
  sudo yum localinstall -y "$path_to_save"
else
  abort "Unsupported system"
fi

rm "$path_to_save"
