#!/usr/bin/env bash
#
# Install gopls (https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation)

set -e

# version="latest"
version="v0.15.3"

cd /tmp && go install golang.org/x/tools/gopls@$version
