#!/usr/bin/env bash
#
# Install helm (https://helm.sh/docs/intro/install/)

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

type -p helm &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

version="3.2.3"
path_to_save="/tmp/helm-$version.tgz"
if is_mac; then
  platform="darwin"
elif is_linux; then
  platform="linux"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://get.helm.sh/helm-v$version-$platform-amd64.tar.gz" $path_to_save
tar zxf $path_to_save -C ~/bin $platform-amd64/helm --strip-components 1
