#!/usr/bin/env bash
#
# Install hstr (https://github.com/dvorka/hstr)

set -eo pipefail

type -p hstr &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  brew_install hstr
elif has_apt; then
  sudo add-apt-repository ppa:ultradvorka/ppa
  sudo apt-get update
  sudo apt-get install -y hstr
elif has_yum; then
  sudo yum install -y hstr
else
  abort "Unsupported system"
fi
