#!/usr/bin/env bash
#
# Install hub (https://github.com/github/hub).

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command hub &> /dev/null && exit

version="2.14.2"
path_to_save="/tmp/hub-$version.tgz"
if is_mac; then
  platform="darwin"
elif is_linux; then
  platform="linux"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://github.com/github/hub/releases/download/v$version/hub-$platform-amd64-$version.tgz" $path_to_save
tar zxf $path_to_save -C /tmp
dir=/tmp/hub-$platform-amd64-$version
cp $dir/bin/hub ~/bin
rm -rf $dir
