#!/usr/bin/env bash
#
# Install libimobiledevice (https://github.com/libimobiledevice/libimobiledevice).

set -eo pipefail

$(dirname "$BASH_SOURCE")/../install/libusbmuxd

. $(dirname "$BASH_SOURCE")/../lib/utils.sh
. $(dirname "$BASH_SOURCE")/../lib/git.sh

dir="/tmp/libimobiledevice"
git_clone "https://github.com/libimobiledevice/libimobiledevice.git" "$dir" --depth 1 -b 1.3.0

cd "$dir"

if has_apt; then
  sudo apt-get install -y \
    build-essential \
    checkinstall \
    git \
    autoconf \
    automake \
    libtool-bin \
    libssl-dev
fi

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
./autogen.sh
make
sudo make install

rm -rf "$dir"
