#!/usr/bin/env bash
#
# If you encounter such error:
#
#   sha256sum: WARNING: 1 computed checksum did NOT match
#
# most probably it's because TUNA only mirrors the latest JDK version for each
# variant. To resolve this issue, please visit
# https://mirrors.tuna.tsinghua.edu.cn/AdoptOpenJDK to find a version and
# execute `asdf list-all java` to get a matched version name, use it to replace
# the Java version in '.tool-versions'.

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../lib/install.sh
. $(dirname "$BASH_SOURCE")/../lib/asdf.sh

$(dirname "$BASH_SOURCE")/jq

# Mirror: https://mirrors.tuna.tsinghua.edu.cn/Adoptium/
#
# How to use a mirror:
# 1. Open `~/.asdf/plugins/java/bin/install`
# 2. Comment `retrieve-release-data`
# 3. Add below code:
#    ```
#    release_data="$(echo -e "adoptopenjdk-21.0.8+9\tOpenJDK21U-jdk_aarch64_mac_hotspot_21.0.8_9.tar.gz\thttps://mirrors.tuna.tsinghua.edu.cn/Adoptium/21/jdk/aarch64/mac/OpenJDK21U-jdk_aarch64_mac_hotspot_21.0.8_9.tar.gz\tchecksum")"
#    ```

install_plugin_package java "$1"
