#!/usr/bin/env bash
#
# Install jq (https://stedolan.github.io/jq/).

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command jq &> /dev/null && exit

version="1.8.1"
if is_mac; then
  brew_install jq
  exit
elif is_linux; then
  if is_arm64; then
    platform="arm64"
  else
    platform="amd64"
  fi
else
  abort "Unsupported system"
fi

install_fn() {
  local file="$1"
  chmod a+x "$file"
  if is_linux; then
    sudo mv "$file" /usr/bin/jq
  else
    mv "$file" "$DOTFILES_TARGET_DIR/bin/jq"
  fi
}

download_and_install "https://github.com/jqlang/jq/releases/download/jq-$version/jq-linux-$platform" install_fn
