#!/usr/bin/env bash
#
# Install kubernetes tools.

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../lib/install.sh

# Multi pod and container log tailing
check_and_install_stern() {
  local platform
  local version="1.11.0"

  if ! which stern &> /dev/null; then
    if is_mac; then
      platform=darwin
    elif is_linux; then
      platform=linux
    else
      return
    fi

    ~/.dotfiles/bin/cget "https://github.com/wercker/stern/releases/download/$version/stern_${platform}_amd64" ~/bin/stern
    chmod a+x ~/bin/stern
  fi
}

check_and_install_stern
