#!/usr/bin/env bash
#
# Install libplist (https://github.com/libimobiledevice/libplist)

set -eo pipefail

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
pkg-config --exists libplist-2.0 && exit

. $(dirname "$BASH_SOURCE")/../lib/utils.sh
. $(dirname "$BASH_SOURCE")/../lib/git.sh

dir="/tmp/libplist"
git_clone "https://github.com/libimobiledevice/libplist.git" "$dir" --depth 1

if has_apt; then
  sudo apt-get install -y \
    build-essential \
    checkinstall \
    autoconf \
    automake \
    libtool-bin
fi

cd "$dir"
./autogen.sh
make
sudo make install

rm -rf "$dir"
