#!/usr/bin/env bash
#
# Install linux source by using tsinghua mirror.

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

version="5.7.6"
path_to_save="/tmp/linux-$version.tar.xz"
"$DOTFILES_DIR/bin/get" "https://mirrors.tuna.tsinghua.edu.cn/kernel/v$(echo $version | awk -F. '{print $1}').x/linux-$version.tar.xz" "$path_to_save"
tar Jxf "$path_to_save" -C /tmp
rm "$path_to_save"
