#!/usr/bin/env bash
#
# Install mihomo (https://github.com/MetaCubeX/mihomo)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

test -x /usr/bin/mihomo && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

version="v1.18.9"
path_to_save="/tmp/mihomo-$version.gz"
if is_linux; then
  platform="linux-amd64"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-$platform-$version.gz" "$path_to_save"

gunzip "$path_to_save"
(cd /tmp && chmod a+x "mihomo-$version" && sudo mv "mihomo-$version" /usr/bin/mihomo)

if is_linux; then
  sudo mkdir -p /usr/local/etc/mihomo
  sudo chown "$(whoami)" /usr/local/etc/mihomo
  sudo cp "$DOTFILES_DIR/mihomo/mihomo.service" /etc/systemd/system

  cat <<EOF
To run mihomo, you need to copy $DOTFILES_DIR/mihomo/config.yaml to /usr/local/etc/mihomo.
To use geoip rule, you need to copy $DOTFILES_DIR/.local/geoip.metadb to /usr/local/etc/mihomo.
EOF
fi
