#!/usr/bin/env bash
#
# Install mitmproxy (https://github.com/mitmproxy/mitmproxy)

set -eo pipefail

type -p mitmproxy &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  brew_install mitmproxy
else
  abort "Unsupported system"
fi
