#!/usr/bin/env bash
#
# Install mitmproxy (https://github.com/mitmproxy/mitmproxy)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command mitmproxy &> /dev/null && exit

pip install mitmproxy
check_command asdf &>/dev/null && asdf reshim
