#!/usr/bin/env bash
#
# `route` command is provided by net-tools.

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if has_yum; then
  sudo yum install -y net-tools
elif has_apt; then
  sudo apt-get install -y net-tools
fi
