#!/usr/bin/env bash
#
# Install ninja (https://ninja-build.org/)

type -p ninja &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../utils.sh

version="1.10.0"
path_to_save="/tmp/ninja-$version.zip"
if is_mac; then
  platform="mac"
elif is_linux; then
  platform="linux"
else
  abort "Unsupported system"
fi

~/.dotfiles/bin/cget "https://github.com/ninja-build/ninja/releases/download/v$version/ninja-$platform.zip" $path_to_save
cd /tmp && unzip $path_to_save
mv /tmp/ninja ~/bin
