#!/usr/bin/env bash

set -eo pipefail

usage() {
  cat <<-EOF
Usage: $0 [version]
EOF
  exit 1
}

. $(dirname "$BASH_SOURCE")/../lib/install.sh
. $(dirname "$BASH_SOURCE")/../lib/asdf.sh

export NODEJS_ORG_MIRROR="https://registry.npmmirror.com/node/"

install_plugin_package nodejs "$1"
