#!/usr/bin/env bash

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../lib/install.sh

packages=(
  curl
  wget
  git
  unzip
  make
  gcc
  automake
  byacc
)

if has_yum; then
  sudo yum install -y "${packages[@]}" libevent libevent-devel
elif has_apt; then
  sudo apt-get install -y "${packages[@]}" libevent-dev
fi
