#!/usr/bin/env bash
#
# Install the prerequisites when setting up this repository.

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../utils.sh

if is_mac; then
  brew_install unzip
elif has_yum; then
  sudo yum install -y unzip
elif has_apt; then
  sudo apt-get install -y unzip
else
  abort "Unsupported system"
fi
