#!/usr/bin/env bash
#
# Install privoxy (https://www.privoxy.org/user-manual/installation.html).

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command privoxy &> /dev/null && exit

if is_mac; then
  brew_install privoxy
else
  abort "Unsupported system"
fi
