#!/usr/bin/env bash
#
# Install protoc (https://github.com/protocolbuffers/protobuf) and related plugins.

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if ! check_command protoc &> /dev/null; do
  version="3.17.3"
  path_to_save="/tmp/protoc-$version.tgz"
  if is_mac; then
    platform="osx"
  elif is_linux; then
    platform="linux"
  else
    abort "Unsupported system"
  fi

  "$DOTFILES_DIR/bin/get" "https://github.com/protocolbuffers/protobuf/releases/download/v$version/protoc-$version-$platform-x86_64.zip" "$path_to_save"
  unzip "$path_to_save" bin/protoc -d "$HOME"
  rm -rf "$path_to_save"
done

# Install go plugin for protoc.
# See https://developers.google.com/protocol-buffers/docs/reference/go-generated
if ! type -p protoc-gen-go && type -p go; then
  go get google.golang.org/protobuf/cmd/protoc-gen-go@latest
fi
