#!/usr/bin/env bash
#
# Install pwntools (https://docs.pwntools.com/en/stable/install.html)

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../lib/install.sh

is_mac && $(dirname "$BASH_SOURCE")/binutils-for-osx

type -p pwn &> /dev/null && exit

pip install pwntools
asdf reshim
