#!/usr/bin/env bash
#
# Install RealVNC Viewer (https://www.realvnc.com/en/connect/download/viewer/)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

[[ -x "/Applications/VNC Viewer.app/Contents/MacOS/vncviewer" ]] && exit

if is_mac; then
  brew_install --cask vnc-viewer
else
  abort "Unsupported system"
fi
