#!/usr/bin/env bash
#
# Install rg (https://github.com/BurntSushi/ripgrep)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command rg &> /dev/null && exit

if is_termux; then
  pkg install ripgrep
  exit
fi

if [ -z "$DOTFILES_NON_INTRUSIVE_MODE" ]; then
  if is_mac; then
    brew_install ripgrep
  elif has_yum; then
    sudo yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo
    sudo yum install -y ripgrep
  elif has_dpkg; then
    version=12.1.1
    download_and_install_debian_package "https://github.com/BurntSushi/ripgrep/releases/download/$version/ripgrep_${version}_amd64.deb"
  else
    abort "Unsupported system"
  fi
else
  version="14.0.3"
  if is_arm64; then
    if is_mac; then
      platform="aarch64-apple-darwin"
    else
      platform="aarch64-unknown-linux-gnu"
    fi
  else
    if is_mac; then
      platform="x86_64-apple-darwin"
    else
      platform="x86_64-unknown-linux-musl"
    fi
  fi
  install_fn() {
    local dir="$(find "$1" -maxdepth 1 -type d | grep -v '^\.$' | tail -1)"
    cd "$dir" && mv rg "$DOTFILES_TARGET_DIR/bin"
  }
  download_and_install "https://github.com/BurntSushi/ripgrep/releases/download/$version/ripgrep-$version-$platform.tar.gz" install_fn
fi
