#!/usr/bin/env bash
#
# Install rlwrap

set -eo pipefail

type -p rlwrap &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  brew_install rlwrap
elif has_yum; then
  sudo yum install -y rlwrap
elif has_apt; then
  sudo apt-get install -y rlwrap
else
  abort "Unsupported system"
fi
