#!/usr/bin/env bash

set -eo pipefail

usage() {
  cat <<-EOF
Usage: $0 [version]
EOF
  exit 1
}

remainder=()
while [ $# -gt 0 ]; do
  case "$1" in
    -*)
      usage
      ;;
    *)
      remainder+=("$1")
      ;;
  esac
  shift
done
set - "${remainder[@]}"

. $(dirname "$BASH_SOURCE")/../lib/install.sh
. $(dirname "$BASH_SOURCE")/../lib/asdf.sh

echo 'Check and install ruby dependencies...'
if has_yum; then
  sudo yum install -y openssl-devel readline-devel
elif has_apt; then
  sudo apt-get install -y libssl1.0-dev libreadline-dev
fi

mirror_cmd() {
  local package_url="$1"
  local checksum="$2"

  echo "${package_url/cache.ruby-lang.org/cache.ruby-china.com}"
}

export -f mirror_cmd
export RUBY_BUILD_MIRROR_CMD=mirror_cmd

install_plugin_package ruby "$1"
