#!/usr/bin/env bash
#
# Install scoop packages.

. $(dirname "$BASH_SOURCE")/../utils.sh
. $(dirname "$BASH_SOURCE")/../lib/scoop.sh

scoop install coreutils
scoop install https://github.com/lukesampson/scoop-extras/blob/master/bucket/pasteboard.json
