#!/usr/bin/env bash
#
# Install scoop packages.

. $(dirname "$BASH_SOURCE")/../lib/install.sh

scoop="$(dirname "$BASH_SOURCE")/../../bin/scoop"

"$scoop" install coreutils
"$scoop" install https://github.com/lukesampson/scoop-extras/blob/master/bucket/pasteboard.json

"$scoop" bucket add extras

# Offline documentation browser. See: https://zealdocs.org/download.html
"$scoop" install zeal
