#!/usr/bin/env bash
#
# Install sqlite3 (https://sqlite.org/download.html)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

usage() {
  cat <<-EOF
Install sqlite3.

Options:
  --local-install Install to user home directory
  --force-install Force to install even if it already exists
  --temp-dir <dir> Temp dir to store the src and build files
EOF
  exit 1
}

parse_args="
  --local-install)
    local_install=1
    ;;
  --force-install)
    force_install=1
    ;;
  --temp-dir)
    shift
    temp_dir=\"\$1\"
    ;;
  *)
    usage
    ;;
"

source "$DOTFILES_DIR/scripts/lib/install.sh"

[ -z "$force_install" ] && check_command sqlite3 &> /dev/null && exit

install_fn() {
  local dir="$(find "$1" -maxdepth 1 -type d | grep -v '^\.$' | tail -1)"
  cd "$dir"

  if [ -z "$local_install" ]; then
    ./configure
  else
    ./configure --prefix="$DOTFILES_TARGET_DIR/opt"
  fi
  make
  make install
}
download_and_install "https://sqlite.org/2023/sqlite-autoconf-3440000.tar.gz" install_fn "$temp_dir"
