#!/usr/bin/env bash
#
# Install sshuttle (https://sshuttle.readthedocs.io/en/stable/installation.html)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command sshuttle &> /dev/null && exit

version="v1.0.5"
dir="/tmp/sshuttle"
git_clone "https://github.com/sshuttle/sshuttle" "$dir" -b "$version" --depth 1

(cd "$dir"; ./setup.py install)
rm -rf "$dir"

asdf reshim
