#!/usr/bin/env bash
#
# Install sshuttle (https://sshuttle.readthedocs.io/en/stable/installation.html)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command sshuttle &> /dev/null && exit

install_fn() {
  cd "$1"

  rm -rf .tool-versions
  ln -s "$DOTFILES_DIR/tool-versions" .tool-versions
  ./setup.py install
  asdf reshim
}

version="v1.1.2"
download_and_install_by_git "https://github.com/sshuttle/sshuttle" install_fn "" -b "$version"
