#!/usr/bin/env bash
#
# Multi pod and container log tailing

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

type -p stern &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  platform=darwin
elif is_linux; then
  platform=linux
else
  abort "Unsupported system"
fi

version="1.11.0"
"$DOTFILES_DIR/bin/get" "https://github.com/wercker/stern/releases/download/$version/stern_${platform}_amd64" ~/bin/stern
chmod a+x ~/bin/stern
