#!/usr/bin/env bash
#
# Install termshark (https://github.com/gcla/termshark).
# A terminal user-interface for tshark, inspired by Wireshark.

set -eo pipefail

go install github.com/gcla/termshark/v2/cmd/termshark@latest
