#!/usr/bin/env bash
#
# Install tmux (https://github.com/tmux/tmux)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

usage() {
  cat <<-EOF
Install tmux.

Options:
  --from-git-repo Install from git repo
  --install-plugins Install plugins
  --local-install Install to user home directory
  --force-install Force to install even if it already exists
EOF
  exit 1
}

parse_args="
  --from-git-repo)
    from_git_repo=1
    ;;
  --install-plugins)
    install_plugins=1
    ;;
  --local-install)
    local_install=1
    ;;
  --force-install)
    force_install=1
    ;;
  *)
    usage
    ;;
"

source "$DOTFILES_DIR/scripts/lib/install.sh"

[ -z "$force_install" ] && check_command tmux &> /dev/null && exit

check_plugins() {
  [ -z "$install_plugins" ] && return

  local plugin
  while read plugin; do
    local dir="$DOTFILES_TARGET_DIR/.config/tmux/plugins/$(basename "$plugin")"
    if [ -z "$(ls "$dir" 2>/dev/null || true)" ]; then
      git clone --depth 1 "https://github.com/$plugin" "$dir"
    fi
  done < <(cat "$DOTFILES_DIR/config/tmux/tmux.conf" | grep '^set-option -g @plugin' | cut -d ' ' -f 4 | sed "s/'//g")
}

[ -z "$force_install" ] && check_command tmux &> /dev/null && check_plugins && exit

if [ -z "$DOTFILES_NON_INTRUSIVE_MODE" -a -z "$local_install" ] && is_mac; then
  brew_install tmux
  exit
fi

version="3.3a"

if has_apt; then
  # Required for copying to system clipboard.
  sudo apt-get install -y clip || true
elif has_yum; then
  sudo yum install -y libevent-devel
fi

do_install() {
  cd "$1"

  if [ ! -e configure ] && [ -e autogen.sh ]; then
    sh autogen.sh
  fi

  local dest_path="$DOTFILES_TARGET_DIR/opt/tmux-$version"
  local -a opts
  if is_mac; then
    opts+=(--enable-utf8proc)
  fi
  ./configure --prefix "$dest_path" "${opts[@]}"
  make
  make install
  local link="$DOTFILES_TARGET_DIR/bin/tmux"
  [ -e "$link" ] && rm -rf "$link"
  mkdir -p "$dest_path/bin"
  create_link "$link" "$dest_path/bin/tmux"
}

if [ -n "$from_git_repo" ]; then
  dir="/tmp/tmux-$version"
  git_clone https://github.com/tmux/tmux.git "$dir" --branch "$version" --depth 1

  do_install "$dir"
  rm -rf "$dir"
else
  install_fn() {
    local dir="$(find "$1" -maxdepth 1 -type d | grep -v '^\.$' | tail -1)"
    do_install "$dir"
  }
  download_and_install "https://github.com/tmux/tmux/releases/download/$version/tmux-$version.tar.gz" install_fn
fi

install_plugins=1
check_plugins
