#!/usr/bin/env bash
#
# Install tor onion service (https://community.torproject.org/onion-services/setup/install/)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command tor &> /dev/null && exit

if is_mac; then
  brew_install tor
elif has_apt; then
  sudo apt-get install -y tor
else
  abort "Unsupported system"
fi
