#!/usr/bin/env bash
#
# Install tor onion service (https://community.torproject.org/onion-services/setup/install/)

set -eo pipefail

type -p tor &> /dev/null && exit

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if is_mac; then
  brew_install tor
elif has_apt; then
  sudo apt-get install tor
else
  abort "Unsupported system"
fi
