#!/usr/bin/env bash
#
# Install utility packages.

set -eo pipefail

. $(dirname "$BASH_SOURCE")/../utils.sh

if has_yum; then
  sudo yum install -y whois
elif has_apt; then
  sudo apt-get install -y whois
fi
