#!/usr/bin/env bash
#
# Install vim.

set -eo pipefail

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

. "$dotfiles_dir/scripts/lib/install.sh"

usage() {
  cat <<-EOF
Install vim from source.

Options:
  -v <version>
EOF
  exit 1
}

version="master"
while [ "$#" -gt 0 ]; do
  case "$1" in
    -v)
      shift
      version="$1"
      ;;
    *)
      usage
      ;;
  esac
  shift
done

install_from_source() {
  local dest_dir="$HOME/vim-$version"
  if [ -f "$dest_dir/bin/vim" ]; then
    echo "Already installed at $dest_dir"
    return
  fi

  local dir="/tmp/vim"
  git_clone "https://github.com/vim/vim.git" "$dir" -b "$version" --depth 1

  (cd "$dir"; ./configure --prefix="$dest_dir" --disable-libsodium --enable-python3interp; make; make install; rm -rf "$dir")
}

install_from_source
