#!/usr/bin/env bash
#
# Install wabt (https://github.com/webassembly/wabt)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

. $(dirname "$BASH_SOURCE")/../lib/install.sh

check_command wat2wasm &> /dev/null && exit

version="1.0.24"
path_to_save="/tmp/wabt-$version.tgz"
if is_mac; then
  platform="macos"
elif is_linux; then
  platform="ubuntu"
else
  abort "Unsupported system"
fi

"$DOTFILES_DIR/bin/get" "https://github.com/WebAssembly/wabt/releases/download/$version/wabt-$version-$platform.tar.gz" "$path_to_save"
tar zxf "$path_to_save" -C ~/bin --strip-components=2 --wildcards "wabt-$version/bin/*"
rm -rf "$path_to_save"
