#!/usr/bin/env bash
#
# Install wabt (https://github.com/webassembly/wabt)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"

. $(dirname "$BASH_SOURCE")/../lib/install.sh

check_command wat2wasm &> /dev/null && exit

version="1.0.36"
path_to_save="/tmp/wabt-$version.tgz"
if is_mac; then
  platform="macos-14"
elif is_linux; then
  platform="ubuntu-20.04"
else
  abort "Unsupported system"
fi

install_fn() {
  mv "$1"/wabt-$version/bin/* ~/bin
}
download_and_install "https://github.com/WebAssembly/wabt/releases/download/$version/wabt-$version-$platform.tar.gz" install_fn
