#!/usr/bin/env bash
#
# Install websocat (https://github.com/vi/websocat/)

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

check_command websocat &> /dev/null && exit

if is_mac; then
  brew_install websocat
else
  abort "Unsupported system"
fi
