#!/usr/bin/env bash
#
# Install words (https://en.wikipedia.org/wiki/Words_(Unix))

. $(dirname "$BASH_SOURCE")/../lib/install.sh

if has_yum; then
  sudo yum install -y words
else
  abort "Unsupported system"
fi
