#!/usr/bin/env bash
#
# Install xvfb and x11vnc

set -eo pipefail

export DOTFILES_DIR="${DOTFILES_DIR:-$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)}"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/install.sh"

if has_apt; then
  sudo apt-get install -y xvfb x11vnc xdotool xclip
elif has_yum; then
  sudo yum install -y xorg-x11-server-Xvfb x11vnc xdotool xclip
else
  abort "Unsupported system"
fi
