#!/usr/bin/env bash

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --created)
      container_status="created"
      ;;
    --exited)
      container_status="exited"
      ;;
  esac
  shift
done

if [ -z "$container_status" ]; then
  echo 'To remove docker containers, you must specify either --created or --exited option.'
  exit 1;
fi

if [ "$container_status" = "exited" ]; then
  source "$dotfiles_dir/scripts/lib/prompt.sh"
  ask_for_input exit_before "Exit before (e.g. 1h, 1 hour, 2d, 2 weeks, 5m, 3year): "
  echo $exit_before
fi

lines="$(docker ps --filter="status=$container_status" --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}" | sed 1d)"

perl "$(dirname "$BASH_SOURCE")/rm_containers.pl" "$lines" "$exit_before"
