#!/usr/bin/env bash

export no_proxy
export ssh_pub_key
export setup_system_repo_mirror

while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-proxy)
      no_proxy=1
      ;;
    --ssh-pub-key)
      shift
      ssh_pub_key="$1"
      ;;
    --setup-system-repo-mirror)
      setup_system_repo_mirror=1
      ;;
  esac
  shift
done

args_file="/tmp/setup_args.env"

if [ "$(whoami)" = "root" ]; then
  echo "Switch to a default user"
#__ADD_USER_SCRIPT_STUB__
  cat <<EOF >"$args_file"
no_proxy="$no_proxy"
ssh_pub_key="$ssh_pub_key"
setup_system_repo_mirror="$setup_system_repo_mirror"
EOF

  su -l "$default_user_name"
fi

args_file="/tmp/setup_args.env"
if [ -e "$args_file" ]; then
  source "$args_file"
  sudo rm "$args_file"
fi

set -eo pipefail

DOTFILES_PARENT_DIR="$HOME/tmp"
DOTFILES_DIR="$DOTFILES_PARENT_DIR/dotfiles"

mkdir -p "$DOTFILES_PARENT_DIR"

if [ -z "$no_proxy" ]; then
  export http_proxy=http://localhost:8123
  export HTTP_PROXY=$http_proxy
  export https_proxy=$http_proxy
  export HTTPS_PROXY=$http_proxy
fi

is_available() {
  type -p "$1" &> /dev/null
}

if [ -n "$setup_system_repo_mirror" ]; then
#__SETUP_SYSTEM_REPO_MIRROR_SCRIPT_STUB__
fi

if ! is_available git; then
  if is_available apt-get; then
    if ! sudo apt-get install -y git; then
      sudo apt-get update
      sudo apt-get install -y git
    fi
  elif is_available yum; then
    sudo yum install -y git
  elif is_available brew; then
    # TODO Actually for mac, we should install brew if it is unavailable.
    brew install git
  else
    echo "You must have git installed."
    exit 1
  fi
fi

if [ -d "$DOTFILES_DIR" ]; then
  cd "$DOTFILES_DIR"
  git pull
else
  git clone --depth 1 https://github.com/uzxmx/dotfiles.git "$DOTFILES_DIR"
  cd "$DOTFILES_DIR"
fi

if [ -n "$ssh_pub_key" ]; then
  SSH_PUB_KEY="$ssh_pub_key" "$DOTFILES_DIR/scripts/misc/add_ssh_pub_key"
fi

alias_cmd="alias non_intrusive_shell=\"$DOTFILES_DIR/scripts/misc/non_intrusive_shell\""

if ! grep "$alias_cmd" ~/.bashrc &>/dev/null; then
  echo "$alias_cmd" >>~/.bashrc
fi

"$DOTFILES_DIR/scripts/misc/non_intrusive_shell" -s <<'EOF'
  # The shell may not be interactive and '.zshrc' won't get loaded. So we source
  # it manually.
  source $DOTFILES_TARGET_DIR/.zshrc

  echo "---- Setup fzf ----"
  $DOTFILES_DIR/scripts/install/fzf
  echo "---- Setup fzf done ----"

  echo "---- Setup fd ----"
  $DOTFILES_DIR/scripts/install/fd
  echo "---- Setup fd done ----"

  echo "---- Setup rg ----"
  $DOTFILES_DIR/scripts/install/rg
  echo "---- Setup rg done ----"

  echo "---- Setup nvim ----"
  $DOTFILES_DIR/scripts/install/nvim --do-all-steps
  echo "---- Setup nvim done ----"

  echo "---- Setup tmux ----"
  $DOTFILES_DIR/scripts/install/tmux --install-plugins
  echo "---- Setup tmux done ----"
EOF
