#!/usr/bin/env bash

DOTFILES_DIR=${DOTFILES_DIR:-~/.dotfiles}
GIT_CLONE_ARGS=($GIT_CLONE_ARGS)

is_available() {
  type -p "$1" &> /dev/null
}

# The only required dependency is `git`.
if ! is_available git; then
  if is_available apt-get; then
    sudo apt-get install -y git
  elif is_available yum; then
    sudo yum install -y git
  elif is_available brew; then
    # TODO Actually for mac, we should install brew if it is unavailable.
    brew install git
  else
    echo 'Unsupported system'
    exit 1
  fi
fi

if [ ! -d "$DOTFILES_DIR" ] || ! (cd "$DOTFILES_DIR" && git status &> /dev/null); then
  if [ "$GIT_CLONE_WITH_SSH" = "1" ]; then
    url="git@github.com:uzxmx/dotfiles.git"
  else
    url="https://github.com/uzxmx/dotfiles.git"
  fi
  run_with_proxy git clone "${GIT_CLONE_ARGS[@]}" "$url" "$DOTFILES_DIR"
elif [ "$update_repo" = "1" ]; then
  (cd "$DOTFILES_DIR" && run_with_proxy git pull)
fi
