let g:vim_home = get(g:, 'vim_home', expand('~/.vim/'))

exe 'source' g:vim_home . 'plugins.vim'

let config_list = [
     \ 'config.vim',
     \ 'mappings.vim',
     \ 'plugin_settings/*.vim'
     \]
for config in config_list
  for file in glob(g:vim_home . config, 1, 1)
    exe 'source' file
  endfor
endfor

silent! exe 'source' g:vim_home . 'vimrc.generated'
silent! exe 'source' g:vim_home . 'vimrc.local'
