let g:current_colorscheme = 'solarized dark'

" set runtimepath^=/projects/coc-java-debug

let mapleader = "\<Space>"
let maplocalleader = "\<Space>"

silent! exe 'source' g:vim_home . '/vimrc.generated'
silent! exe 'source' g:vim_home . '/vimrc.before.local'

exe 'source' g:vim_home . '/plugins.vim'

let config_list = [
     \ 'config.vim',
     \ 'colorscheme.vim',
     \ 'mappings.vim',
     \ 'plugin_settings/*.vim'
     \]
for config in config_list
  for file in glob(g:vim_home . '/' . config, 1, 1)
    exe 'source' file
  endfor
endfor

silent! exe 'source' g:vim_home . '/vimrc.after.local'
