#!/usr/bin/env bash

dotfiles_dir="$(realpath "$(dirname "$BASH_SOURCE")/../..")"

source "$dotfiles_dir/scripts/lib/utils.sh"

if is_wsl; then
  wslsudo vi /mnt/c/Windows/System32/drivers/etc/hosts
  # TODO sync with /etc/hosts
else
  sudo vi /etc/hosts
fi
