#!/usr/bin/env bash

set -eo pipefail

export DOTFILES_DIR="$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)"
export DOTFILES_TARGET_DIR="${DOTFILES_TARGET_DIR:-$HOME}"

source "$DOTFILES_DIR/scripts/lib/utils.sh"
source "$DOTFILES_DIR/scripts/lib/template.sh"
source "$DOTFILES_DIR/scripts/lib/asdf.sh"

SOLARGRAPH_PATH="$DOTFILES_TARGET_DIR/.asdf/shims/solargraph"
LOMBOK_JAR_PATH="$DOTFILES_TARGET_DIR/lombok/lombok.jar"

mkdir -p "$DOTFILES_TARGET_DIR/.config/nvim"
render_shell_template_file "$DOTFILES_DIR/config/nvim/coc-settings.json.tpl.sh" >"$DOTFILES_TARGET_DIR/.config/nvim/coc-settings.json"
