#!/usr/bin/env bash
#
# Initialize workspace. Can be run many times without harm.

. $(dirname "$BASH_SOURCE")/../lib/utils.sh

mkdir -p ~/.dotfiles/.local
mkdir -p ~/projects
mkdir -p ~/go/src/github.com/uzxmx
mkdir -p ~/tmp

if [ ! -e ~/.zshrc.local ]; then
  ~/.dotfiles/scripts/init_zshrc_local
fi
