#!/usr/bin/env bash

set -eo pipefail

export DOTFILES_DIR="$(cd -- "$(dirname "$0")/../.." &>/dev/null && pwd -P)"
export DOTFILES_NON_INTRUSIVE_MODE=1
export DOTFILES_TARGET_DIR="$DOTFILES_DIR/.local"

mkdir -p "$DOTFILES_TARGET_DIR"

source "$DOTFILES_DIR/scripts/lib/path.sh"
PATH="$DOTFILES_TARGET_DIR/bin:$PATH"
if ! check_command zsh &>/dev/null; then
  echo "Zsh not found. Installing..."
  log_file="$DOTFILES_TARGET_DIR/.install.log"
  echo "Log can be found at $log_file"
  if ! "$DOTFILES_DIR/scripts/install/zsh" &>"$log_file"; then
    echo -e "Failed to install zsh.\n"
    tail -50 "$log_file"
    exit 1
  fi
  echo 'Zsh installed successfully.'
fi

if [ ! -e "$DOTFILES_TARGET_DIR/.zshrc" ]; then
  echo "Linking RC files..."
  "$DOTFILES_DIR/bin/rcup"
  echo "Finished linking RC files."
fi

if [ ! -e "$DOTFILES_TARGET_DIR/.zsh_plugins.sh" ]; then
  echo "Building zsh plugins..."
  "$DOTFILES_DIR/bin/antibody" bundle
  echo "Finished building zsh plugins."
fi

exec "$DOTFILES_DIR/bin_nim/zsh" "$@"
