#!/usr/bin/env bash

if type -p apt-get &> /dev/null; then
  # The main archive is for amd64, i386.
  # `ports` is for architectures, which include arm64, armhf, s390x, riscv64, ppc64el.

  # sudo sed -i.bak -Ee 's:[0-9a-zA-Z\.]+\.ubuntu\.com/ubuntu/:mirrors.tuna.tsinghua.edu.cn/ubuntu/:' \
  #   /etc/apt/sources.list

  sudo sed -i.bak -Ee 's:[0-9a-zA-Z\.]+\.ubuntu\.com/ubuntu/:mirrors.aliyun.com/ubuntu/:' \
    -e 's:[0-9a-zA-Z\.]+\.ubuntu\.com/ubuntu-ports/:mirrors.aliyun.com/ubuntu-ports/:' \
    /etc/apt/sources.list

  sudo apt-get update
elif type -p yum &> /dev/null; then
  # sudo sed -i.bak -e 's;^mirrorlist=;#mirrorlist=;' \
  #   -e 's;^#baseurl=http://mirror\.centos\.org;baseurl=https://mirrors.tuna.tsinghua.edu.cn;' \
  #   /etc/yum.repos.d/CentOS-Base.repo

  sudo curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
  sudo sed -i -e '/mirrors.cloud.aliyuncs.com/d' -e '/mirrors.aliyuncs.com/d' /etc/yum.repos.d/CentOS-Base.repo

  sudo yum makecache

  # Install required repos for centos.

  # sudo yum install -y epel-release
  # sudo sed -i.bak -e 's;^metalink=;#metalink=;' \
  #   -e 's;^#baseurl=http://download\.fedoraproject\.org/pub;baseurl=https://mirrors.tuna.tsinghua.edu.cn;' \
  #   /etc/yum.repos.d/epel.repo \
  #   /etc/yum.repos.d/epel-testing.repo

  sudo curl -o /etc/yum.repos.d/epel.repo https://mirrors.aliyun.com/repo/epel-7.repo

  # TODO this cannot be found.
  # sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
  #
  # sudo sed -i.bak -e 's;^baseurl = https://repo\.ius\.io;baseurl = https://mirrors.tuna.tsinghua.edu.cn/ius;' \
  #   /etc/yum.repos.d/ius.repo

  sudo yum install -y centos-release

  # sudo sed -i.bak -e 's;http://vault.centos.org;https://mirrors.tuna.tsinghua.edu.cn/centos-vault;' \
  #   /etc/yum.repos.d/CentOS-Vault.repo

  sudo sed -i.bak -e 's;http://vault.centos.org;https://mirrors.aliyun.com/centos-vault;' \
    /etc/yum.repos.d/CentOS-Vault.repo
fi
