#!/usr/bin/env bash
#
# Get the IP that shows in tmux status bar.

set -eo pipefail

# For vagrant boxes, we want to show the IP which is accessible from the host.
# And we assume the second nic has such IP when it is available.
if [ -e /home/vagrant ] && ifconfig eth1 &>/dev/null; then
  nic=eth1
else
  nic=eth0
fi

ifconfig "$nic" | grep "inet " | awk '{print $2}'
