#!/bin/sh

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=v2ray
if ! v2ray_path=$(which v2ray); then
  echo v2ray not found
  exit
fi
config_path=/usr/local/etc/v2ray/config.json
pid_path=/var/run/v2ray.pid
log_path=/var/log/v2ray.log

. /lib/lsb/init-functions

start() {
  local result
  if ! result=$("$v2ray_path" -test -c "$config_path"); then
    echo "$result"
    exit
  fi
  start-stop-daemon --start --quiet --oknodo --pidfile "$pid_path" -m --exec "$v2ray_path" -- -c "$config_path" >"$log_path" 2>&1 &
}

stop() {
  start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_path" --remove-pidfile
}

case "$1" in
  start)
    start
    echo "$NAME started."
    ;;
  stop)
    stop
    echo "$NAME stopped."
    ;;
  status)
    status_of_proc -p "$pid_path" v2ray v2ray
    ;;
  restart|force-reload)
    stop
    start
    echo "$NAME restarted."
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
