#!/usr/bin/env bash

set -eo pipefail

version="${1:-2.18}"
path_to_save="${2:-/tmp/glibc-$version.tar.gz}"
~/.dotfiles/bin/cget "http://mirrors.ustc.edu.cn/gnu/libc/glibc-$version.tar.gz" "$path_to_save"
