#!/usr/bin/env bash

set -eo pipefail

if [ -z "$DOTFILES_DIR" ]; then
  DOTFILES_DIR="$(cd -- "$(dirname "$0")/.." &>/dev/null && pwd -P)"
fi

source "$DOTFILES_DIR/scripts/lib/path.sh"
PATH="$(new_path_exclude "$DOTFILES_DIR/bin_nim")"

export XDG_CONFIG_HOME="$DOTFILES_DIR/.local/.config"

exec nvim "$@"
