#!/usr/bin/env bash
#
# This script will be evaluated after `rcup` finishes.

warn() {
  echo $@
}

abort() {
  echo $@ >>/dev/stderr
  exit 1
}

case $OSTYPE in
  darwin*)
    platform=osx
    ;;
esac

if [ -n "$platform" -a -f ~/.zshrc.$platform ]; then
  if [ -f ~/.zshrc.platform ]; then
    if [ $? != 0 -o "$(readlink ~/.zshrc.platform)" != "$(ls -d ~)/.zshrc.$platform" ]; then
      warn "Failed to link ~/.zshrc.platform to ~/.zshrc.$platform, please check ~/.zshrc.platform"
    fi
  else
    ln -s ~/.zshrc.$platform ~/.zshrc.platform
  fi
fi


erb $(dirname $0)/../config/nvim/coc-settings.json.erb >~/.config/nvim/coc-settings.json

echo -n 'Checking antibody...'
if type antibody &>/dev/null; then
  echo 'Found'
else
  echo 'Not found, installing...'
  curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
  antibody bundle <~/.dotfiles/zsh/plugins.txt >~/.zsh_plugins.sh
fi

echo -n 'Checking js-beautify for vim-autoformat json...'
if type js-beautify &>/dev/null; then
  echo 'Found'
else
  echo 'Not found, installing...'
  npm install -g js-beautify
  echo 'Done'
fi

echo -n 'Checking fzf...'
if type fzf &>/dev/null; then
  echo 'Found'
else
  echo 'Not found, installing...'
  if `$(dirname $0)/../scripts/install_fzf.sh >/dev/null`; then
    echo 'Done'
  else
    exit 1
  fi
fi

echo -n 'Checking fd...'
if type fd &>/dev/null; then
  echo 'Found'
else
  echo 'Not found, installing...'
  if `$(dirname $0)/../scripts/install_fd.sh >/dev/null`; then
    echo 'Done'
  else
    exit 1
  fi
fi
