#!/usr/bin/env zsh
#
# This script will be evaluated before `rcup` starts.

. $(dirname "$0")/../scripts/lib/prompt.sh
. $(dirname "$0")/../scripts/lib/utils.sh

if [[ ! -d ~/bin ]]; then
  mkdir ~/bin
fi

# Link vi to nvim.
if type -p nvim &>/dev/null; then
  nvim_path="$(which nvim)"
  is_link ~/bin/vi "$nvim_path" || create_link ~/bin/vi "$nvim_path"
fi

# If ~/.gitconfig is not a link to ~/.dotfiles/gitconfig, we just append its content to
# ~/.dotfiles/gitconfig when we still want to make a link later.
if [ -f ~/.gitconfig -a "$(readlink ~/.gitconfig)" != "$(ls -d ~)/.dotfiles/gitconfig" ]; then
  info '~/.gitconfig exists, append its content to ~/.dotfiles/gitconfig'
  cat ~/.gitconfig >>~/.dotfiles/gitconfig
fi

[[ -z "$SKIP_ASDF" ]] && ../scripts/setup_asdf.sh
