#!/usr/bin/env bash

. $(dirname "$BASH_SOURCE")/utils.sh

while getopts 'f' opt; do
  case "$opt" in
    f)
      force=true
      ;;
    *)
      abort "Unknown option: $opt"
      ;;
  esac
done

if [ -f ~/.zshrc.local ]; then
  if [ -n "$force" ]; then
    rm ~/.zshrc.local
  else
    abort 'You need to remove ~/.zshrc.local before generating a new one, or use -f option to force it.'
  fi
fi

erb -T - ~/.dotfiles/zshrc.local.erb > ~/.zshrc.local
