#!/usr/bin/env bash
#
# Setup tmux

set -eo pipefail

while read plugin; do
  dir=~/.tmux/plugins/$(basename $plugin)
  if [ -z "$(ls $dir 2>/dev/null || true)" ]; then
    git clone --depth 1 https://github.com/$plugin $dir
  fi
done < <(cat ~/.dotfiles/tmux.conf | grep '^set-option -g @plugin' | cut -d ' ' -f 4 | sed "s/'//g")
