#!/usr/bin/env bash
#
# This script helps you manage tmux.

set -eo pipefail

usage() {
  echo "Usage: $0 <new | attach | detach>" >&2
  exit 1
}

fatal() {
  echo "$@" >&2
  exit 1
}

is_in_tmux_session() {
  [ -n "$TMUX" ]
}

session_exists() {
  tmux list-sessions -F '#{session_name}' 2>/dev/null || true | grep "^$1$"
}

new() {
  local session_name="$1"
  if [ -z "$session_name" ]; then
    session_name="default"
    if session_exists "$session_name" &>/dev/null; then
      session_name=
    fi
  fi

  if [ -z "$session_name" ]; then
    session_name=$(rlwrap -S "Session name: " -o cat)
  fi

  if [ -z "$session_name" ]; then
    tmux new-session
  else
    tmux new-session -s "$session_name"
  fi
}

attach() {
  local IFS=$'\n'
  sessions=($(tmux list-sessions 2>/dev/null || true))
  if [ -z "$sessions" ]; then
    new
    return
  fi

  if [ "${#sessions[@]}" = "1" ]; then
    session="${sessions[0]}"
  else
    session="$(echo "${sessions[*]}" | fzf)"
  fi

  name="$(echo "$session" | cut -d ":" -f 1)"
  if is_in_tmux_session; then
    tmux switch -t "$name"
  else
    tmux attach -t "$name"
  fi
}

detach() {
  if ! is_in_tmux_session; then
    fatal "Failed to detach, because you are currently not in a Tmux session."
  fi
  tmux detach
}

case "$1" in
  new | attach | detach)
    $1
    ;;
  *)
    usage
    ;;
esac
