source "$DOTFILES_DIR/scripts/lib/fzf.sh"
source "$DOTFILES_DIR/scripts/lib/utils/lines_to_array.sh"
source "$DOTFILES_DIR/scripts/lib/utils/join.sh"
source "$DOTFILES_DIR/scripts/lib/utils/split.sh"
source "$DOTFILES_DIR/scripts/lib/utils/capture_source_and_signal.sh"
